In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
data=pd.read_csv("multi_classification_train.csv")
data_test=pd.read_csv("multi_classification_test.csv")

In [12]:
data.head()

ID   Feature_1  Feature_2  Feature_3   Feature_4   Feature_5   Feature_6  \
0   1  -90.532634 -66.953472  79.261856 -111.800554  126.403549  111.509348   
1   2 -103.156720 -16.070400  87.819228   12.614599   51.347780   67.483725   
2   3   24.326153 -92.098078  82.238354  -56.795879   85.203996  127.916504   
3   4  -64.631737 -83.703583  84.135072   -5.516152   74.338494  112.630556   
4   5  -55.473830 -78.853237  88.129107   75.200543   76.991520   60.224711   

    Feature_7   Feature_8   Feature_9  ...  Feature_12  Feature_13  \
0  207.728953  -26.600556 -106.229324  ...  148.391734   77.835738   
1   40.269172   51.442254 -151.486693  ...   29.009475    3.995786   
2  -90.080307 -128.124071   18.036020  ...  111.810098   65.826018   
3  181.576798   -1.054023   60.469865  ...   50.047108  100.439101   
4  -13.106559 -146.773016  -33.490566  ...   85.988282   23.381960   

   Feature_14  Feature_15  Feature_16  Feature_17  Feature_18  Feature_19  \
0  -10.728207    1.100625    1.035362  -87.010809  -16.242297  -32.074925   
1  -10.861630 -142.605726  -25.924592  -86.755351  -36.479749 -130.246619   
2 -101.271203  -44.127749   -7.131464 -105.049759 -130.948256  -43.113523   
3 -117.842955  150.239788 -144.635542 -144.306209  -69.272905  -79.629675   
4   11.876102 -188.296503  -80.323929  -56.757987  -20.314172  -42.625170   

   Feature_20  Class  
0  -17.666026      1  
1  -44.143652      2  
2  -37.330448      4  
3  -51.334456      2  
4  -24.102753      2  

[5 rows x 22 columns]

In [13]:
data_test.head()

ID   Feature_1   Feature_2  Feature_3   Feature_4  Feature_5   Feature_6  \
0   1  -53.837350  -32.645889  88.656704   68.460038  77.278980  170.299440   
1   2  -72.698043  137.186526  85.122064 -135.777642  72.743374   37.159495   
2   3  -87.376758   52.292029  82.285036 -103.899819  76.276041   22.141478   
3   4 -114.053308  -82.064113  87.352300  311.645082  80.806755  158.822556   
4   5 -129.305845  -70.794135  87.318648  -39.995258  91.126015   96.496800   

    Feature_7   Feature_8   Feature_9  ...  Feature_11  Feature_12  \
0  -40.452999  157.171382   81.019740  ...   45.212220   79.052230   
1    1.219229   86.447392  -29.006295  ...   41.602345   68.546653   
2  131.322204   69.009157 -121.703035  ...   50.667553   94.928521   
3  -74.591773  254.856750 -279.480145  ...   63.089374  131.078916   
4    0.578289 -101.344881   17.968593  ...   -3.900131  -63.876158   

   Feature_13  Feature_14  Feature_15  Feature_16  Feature_17  Feature_18  \
0   23.209321 -300.397141  -26.927269   -7.724388  -47.897697  -31.844784   
1  103.288778    0.742860   31.342856   37.431942  -92.965704  -22.113709   
2   60.908583  -30.925963 -119.456062  170.920590   -8.940891  -49.424624   
3   13.590238    3.596146 -220.548262  -77.689231   21.423893  -64.062843   
4   27.123655   43.230208  -76.974733  -91.008909  -91.917865    1.852507   

   Feature_19  Feature_20  
0  -80.670098  -68.257050  
1  -57.311455  -74.076167  
2  -76.538002  -35.694483  
3  -69.416930  -12.109111  
4  -88.130343 -103.909397  

[5 rows x 21 columns]

In [9]:
X=data.iloc[:,1:21].to_numpy()
y=data["Class"].to_numpy()

In [10]:
X,y

(array([[ -90.53263395,  -66.95347161,   79.26185595, ...,  -16.24229669,
          -32.07492465,  -17.66602617],
        [-103.15671956,  -16.07040001,   87.81922753, ...,  -36.47974913,
         -130.24661901,  -44.14365222],
        [  24.32615256,  -92.09807783,   82.23835394, ..., -130.94825564,
          -43.11352279,  -37.33044832],
        ...,
        [ -37.12290449,   -0.885023  ,   86.99002687, ...,  -41.19319101,
          -66.65209662,  -35.86556245],
        [ -81.06584735,   43.82958547,   87.79424775, ...,  -22.31197279,
          -56.10486356,  -71.17497908],
        [ -67.19757637,  -38.81837815,   88.86213941, ...,  -10.17967089,
         -127.6604871 ,  -58.59004816]]),
 array([1, 2, 4, ..., 1, 3, 2]))

In [19]:
data_test.head()

ID   Feature_1   Feature_2  Feature_3   Feature_4  Feature_5   Feature_6  \
0   1  -53.837350  -32.645889  88.656704   68.460038  77.278980  170.299440   
1   2  -72.698043  137.186526  85.122064 -135.777642  72.743374   37.159495   
2   3  -87.376758   52.292029  82.285036 -103.899819  76.276041   22.141478   
3   4 -114.053308  -82.064113  87.352300  311.645082  80.806755  158.822556   
4   5 -129.305845  -70.794135  87.318648  -39.995258  91.126015   96.496800   

    Feature_7   Feature_8   Feature_9  ...  Feature_11  Feature_12  \
0  -40.452999  157.171382   81.019740  ...   45.212220   79.052230   
1    1.219229   86.447392  -29.006295  ...   41.602345   68.546653   
2  131.322204   69.009157 -121.703035  ...   50.667553   94.928521   
3  -74.591773  254.856750 -279.480145  ...   63.089374  131.078916   
4    0.578289 -101.344881   17.968593  ...   -3.900131  -63.876158   

   Feature_13  Feature_14  Feature_15  Feature_16  Feature_17  Feature_18  \
0   23.209321 -300.397141  -26.927269   -7.724388  -47.897697  -31.844784   
1  103.288778    0.742860   31.342856   37.431942  -92.965704  -22.113709   
2   60.908583  -30.925963 -119.456062  170.920590   -8.940891  -49.424624   
3   13.590238    3.596146 -220.548262  -77.689231   21.423893  -64.062843   
4   27.123655   43.230208  -76.974733  -91.008909  -91.917865    1.852507   

   Feature_19  Feature_20  
0  -80.670098  -68.257050  
1  -57.311455  -74.076167  
2  -76.538002  -35.694483  
3  -69.416930  -12.109111  
4  -88.130343 -103.909397  

[5 rows x 21 columns]

In [22]:
X_test=data_test.iloc[:,1:21].to_numpy()
X_test

array([[ -53.83734971,  -32.6458895 ,   88.65670437, ...,  -31.84478415,
         -80.67009828,  -68.25705001],
       [ -72.69804275,  137.18652565,   85.12206387, ...,  -22.11370932,
         -57.31145453,  -74.07616736],
       [ -87.37675817,   52.29202943,   82.28503619, ...,  -49.4246242 ,
         -76.5380021 ,  -35.69448307],
       ...,
       [ -68.19346585,  -29.41732628,   89.77885938, ...,   -9.40912862,
        -108.54906248,  -73.00628847],
       [-106.53373787,  -99.18908011,   82.97141713, ...,  -31.47872486,
        -109.73942126, -127.29108315],
       [ -88.03119387,  -21.02195308,   83.67580673, ...,  -26.31964756,
         -84.08287989,  -30.13499549]])

In [28]:
def knn_classification(X,y,X_test,k=3):
    prediction=[]
    for testpoint in X_test:
        distance=np.sqrt(np.sum((X-testpoint)**2,axis=1))
        k_indices=np.argsort(distance)[:k]
        k_value=[y[i] for i in k_indices]
        prediction.append(np.mean(k_value))
    return prediction


In [29]:
prediction=knn_classification(X,y,X_test,k=3)

In [33]:
prediction=pd.DataFrame(prediction)
pd.set_option('display.max_rows',None)
prediction 

0
0      3.000000
1      1.000000
2      1.000000
3      1.000000
4      2.000000
5      1.000000
6      2.000000
7      3.000000
8      2.000000
9      2.000000
10     3.000000
11     2.000000
12     2.000000
13     2.000000
14     1.000000
15     2.000000
16     3.000000
17     3.000000
18     3.000000
19     2.000000
20     1.000000
21     1.000000
22     2.000000
23     1.000000
24     3.000000
25     0.000000
26     1.000000
27     2.000000
28     4.000000
29     3.000000
30     0.666667
31     1.000000
32     0.000000
33     2.000000
34     2.000000
35     2.666667
36     3.000000
37     1.000000
38     1.000000
39     1.000000
40     1.000000
41     0.666667
42     2.000000
43     3.000000
44     2.000000
45     3.000000
46     2.000000
47     2.000000
48     4.000000
49     1.000000
50     2.000000
51     2.666667
52     2.000000
53     4.000000
54     3.000000
55     3.000000
56     3.000000
57     2.000000
58     2.000000
59     1.000000
60     1.666667
61     2.000000
62     0.000000
63     3.000000
64     4.000000
65     2.000000
66     0.000000
67     4.000000
68     2.000000
69     2.000000
70     2.000000
71     2.000000
72     2.000000
73     3.000000
74     2.000000
75     2.666667
76     3.000000
77     3.000000
78     2.000000
79     2.000000
80     2.000000
81     1.000000
82     2.000000
83     2.000000
84     3.000000
85     2.000000
86     2.000000
87     2.666667
88     3.000000
89     3.000000
90     1.000000
91     2.000000
92     2.000000
93     3.000000
94     3.000000
95     2.000000
96     2.000000
97     2.000000
98     3.000000
99     2.000000
100    1.000000
101    1.000000
102    3.000000
103    2.666667
104    2.000000
105    3.000000
106    1.000000
107    2.000000
108    4.000000
109    3.000000
110    1.333333
111    1.000000
112    1.000000
113    0.000000
114    2.000000
115    1.000000
116    1.000000
117    2.333333
118    4.000000
119    4.000000
120    1.000000
121    3.000000
122    2.666667
123    1.666667
124    2.000000
125    2.000000
126    1.666667
127    2.666667
128    2.000000
129    3.000000
130    3.000000
131    2.000000
132    2.000000
133    4.000000
134    0.000000
135    2.000000
136    2.000000
137    1.333333
138    3.000000
139    2.000000
140    2.000000
141    0.000000
142    3.000000
143    2.000000
144    2.000000
145    1.000000
146    2.000000
147    3.000000
148    1.000000
149    1.000000
150    2.000000
151    0.000000
152    2.000000
153    3.000000
154    1.000000
155    2.666667
156    2.000000
157    3.333333
158    3.000000
159    1.000000
160    2.000000
161    1.000000
162    1.000000
163    1.000000
164    2.000000
165    1.000000
166    1.000000
167    3.000000
168    3.000000
169    2.000000
170    1.333333
171    2.000000
172    3.000000
173    3.666667
174    3.000000
175    3.000000
176    3.000000
177    3.000000
178    3.000000
179    2.000000
180    2.000000
181    1.000000
182    2.000000
183    2.666667
184    4.000000
185    2.000000
186    1.000000
187    2.000000
188    2.666667
189    4.000000
190    3.000000
191    0.000000
192    3.000000
193    4.000000
194    4.000000
195    4.000000
196    2.000000
197    2.000000
198    3.000000
199    0.000000
200    1.000000
201    3.000000
202    1.333333
203    3.000000
204    2.000000
205    2.000000
206    2.666667
207    2.000000
208    1.000000
209    0.000000
210    2.000000
211    3.333333
212    1.000000
213    4.000000
214    2.000000
215    1.000000
216    2.000000
217    1.333333
218    2.000000
219    0.000000
220    2.000000
221    2.000000
222    3.000000
223    2.000000
224    1.666667
225    4.000000
226    1.000000
227    2.000000
228    2.000000
229    3.000000
230    2.000000
231    2.000000
232    2.000000
233    1.666667
234    2.000000
235    2.000000
236    1.000000
237    1.333333
238    1.000000
239    3.000000
240    2.000000
241    1.000000
242    3.000000
243    2.000000
244    2.000000
245    2.000000
246    4.000000
247    1.000000
248    2.000000
249    4.00000

In [46]:
def f1_score(y,y_prediction):
    unique_classes=np.unique(y)
    f1_scores=[]
    total_samples=len(y)
    weights=[]
    for classes in unique_classes:
        tp=np.sum((y_prediction==classes)&(y==classes))
        fp=np.sum((y_prediction==classes)&(y!=classes))
        fn=np.sum((y_prediction!=classes)&(y==classes))
        precision=tp/(tp+fp)if(tp+fp)>0 else 0
        recall=tp/(tp+fn)if(tp+fn)>0 else 0
        f1=2*(precision*recall)/(precision+recall)if(precision+recall)>0 else 0
        f1_scores.append(f1)
        weights_f1=np.sum(np.sum(y==classes)/total_samples)
    weighted_f1=np.sum(np.array(f1_scores)*np.array(weights))
    return weighted_f1

        

In [47]:
f1=f1_score(y,np.array(prediction))
print(f"f1_score_error:{f1}")
        
        

ValueError: operands could not be broadcast together with shapes (5,) (0,) 